export const client = {
  name: "JF Garden Services Ltd",
  tagline: "Professional Garden Services in Bordon — Quality You Can Trust",
  description: "Professional garden services services in Bordon and surrounding areas. Trusted local experts with 16 Google reviews.",
  category: "Garden Services",
  yearEstablished: "2015",
  phone: "",
  email: "",
  website: "",
  address: "",
  city: "Bordon",
  county: "",
  postcode: "",
  basedIn: "Bordon",
  founderName: "",
  founderSurname: "",
  founderRole: "Director",
  facebook: "",
  instagram: "",
  linkedin: "",
  twitter: "",
  googleRating: "4.7",
  reviewCount: "16",
  services: [
    { title: "Garden Design", description: "Bespoke garden designs tailored to your lifestyle and space.", icon: "tree" },
    { title: "Landscaping", description: "Complete hard and soft landscaping to transform your outdoor area.", icon: "shovel" },
    { title: "Paving & Patios", description: "Beautiful paving solutions using premium natural stone and porcelain.", icon: "wall" },
    { title: "Planting Schemes", description: "Year-round colour and interest with expertly curated planting plans.", icon: "flower" },
  ],
  cinematic: {
    frameCount: 181, frameDir: "/frames/", framePrefix: "frame_", frameExtension: ".jpg",
    framePadding: 4, scrollLength: "500vh", mobileFrameCount: 181, mobileFrameDir: "/frames-mobile/",
    scrubSpeed: 0.5, heroStillImage: "/images/hero-still.jpg", heroStillImageMobile: "/images/hero-still-mobile.jpg",
  },
  beforeAfter: { beforeImage: "/images/before.jpg", afterImage: "/images/after.jpg", beforeLabel: "Current Garden", afterLabel: "Our Vision" },
  transformations: [
    { before: "/images/before.jpg", after: "/images/after.jpg", label: "Complete Garden Renovation" },
    { before: "/images/patio-before.jpg", after: "/images/patio-after.jpg", label: "Patio & Fencing" },
    { before: "/images/front-before.jpg", after: "/images/front-after.jpg", label: "Front Garden" },
    { before: "/images/lawn-before.jpg", after: "/images/lawn-after.jpg", label: "Lawn Restoration" },
    { before: "/images/fence-before.jpg", after: "/images/fence-after.jpg", label: "New Fencing" },
    { before: "/images/deck-before.jpg", after: "/images/deck-after.jpg", label: "Decking & Furniture" },
    { before: "/images/path-before.jpg", after: "/images/path-after.jpg", label: "Garden Path" },
    { before: "/images/border-before.jpg", after: "/images/border-after.jpg", label: "Planting Borders" },
    { before: "/images/drive-before.jpg", after: "/images/drive-after.jpg", label: "Driveway" },
  ] as { before: string; after: string; label: string }[],
  reviews: [
    { name: "Gillian Swinburn", rating: 5, text: "Jack, ably assisted by Darrell, did an excellent job making a patio and steps in my awkwardly sloping garden.  They also levelled and turfed a scruffy raised border.  Very professional, hard-working, punctual and helpful.  Highly recommended.", date: "2 years ago" },
    { name: "Jamie Salmon", rating: 5, text: "I needed a gardener for regular maintenance, after some dreamers on price, the usual unreliable newer companies, I was recommended Jack and his team. They are reliable, helpful, efficient, polite, turned up on time and did a thorough job, really happy with it. Two nice lads and they even did a Saturday morning as that was the only time I was free. Can’t recommend them enough.", date: "3 years ago", badge: "Local Guide" },
    { name: "IkIGAI Therapy", rating: 5, text: "Jack and his crew are extremely professional and always keep you informed . I am very satisfied  with the excellent work they completed for our new driveway and always feel so grateful when they have been to do the garden leaving it tidy and well maintained. I can highly recommend them if you are looking for a reliable friendly service . A big thank you Jack and to the lovely team that supports your excellent business. . Grateful to have found you", date: "3 years ago", badge: "Local Guide" },
    { name: "Dan H", rating: 5, text: "Fantastic company. Great competitive price and the work was fast and high quality. Installed the box sleepers and laid a patio extension and deck + pergola. A year later and everything is exactly as it should be with no wear or damage. Exactly what I wanted, perfectly executed.", date: "3 years ago", badge: "Local Guide" },
    { name: "Candida Rom", rating: 5, text: "Jack and Darrell cleared our garden and relaid the patio, paths and gave us gravel with stepping stones. They made raised beds which are lovely. It is now easy to manage and looks good. We are very pleased with the work. They are a good team. They arrived promptly every morning and worked hard all day. They are neat and clean and we will ask them to sort out our front garden when we are ready. They are very polite and helpful.", date: "4 years ago" },
    { name: "Thomas Fisher", rating: 5, text: "Jack and his team were very professional from the quoting stage to completion. They removed old concrete and tarmac driveway, edging borders with railway sleepers and grass with granite sets before putting down scalping and gravel. The transformation has really lifted the whole feel of the front and side of the house and we couldn’t be happier with the final result. Team were friendly and hard working throughout and have already asked them to quote for further work in the garden.", date: "4 years ago" },
  ] as { name: string; rating: number; text: string; date: string; badge?: string }[],
  seo: {
    title: "JF Garden Services Ltd | Professional Garden Services in Bordon",
    description: "Professional garden services in Bordon. 4.7 stars on Google with 16 reviews. Quality workmanship guaranteed.",
  },
};
